version: 0.2
phases:
  pre_build:
    commands:
      - env
      - npm install
  build:
    commands:
      - env
      - npm run compile
      - npm run test
      - cp package*.json dist/
  post_build:
    commands:
      - env
artifacts:
  base-directory: dist
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*