version: 0.2
phases:
  pre_build:
    commands:
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - npm install
  build:
    commands:
      - npm run compile
      - npm run test
      - cp package*.json dist/
artifacts:
  base-directory: dist
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*